Add Korean(ko) translation
matterpoll/matterpoll pull request #301
Opened 2020-06-03 11:57 UTC by potatogim

Add Korean(ko) translation

Signed-off-by: Ji-Hyeon Gim <potatogim@gluesys.com>

2020-09-04 07:21 UTC, kaakaa reviewed
Thank you for your contribution @potatogim, and I'm sorry for late reply.

Your translation seems to be fine, but the format of the file seem to be different from those in other translated languages.  (e.g.: [active.ja.json](https://github.com/matterpoll/matterpoll/blob/master/assets/i18n/active.ja.json))

Did you follow the steps in [Translation process for new languages](https://github.com/matterpoll/matterpoll/blob/master/CONTRIBUTING.md#translation-process-for-new-languages) to create the file?

2020-09-08 07:35 UTC, potatogim commented
> Thank you for your contribution @potatogim, and I'm sorry for late reply.
> 
> Your translation seems to be fine, but the format of the file seem to be different from those in other translated languages. (e.g.: [active.ja.json](https://github.com/matterpoll/matterpoll/blob/master/assets/i18n/active.ja.json))
> 
> Did you follow the steps in [Translation process for new languages](https://github.com/matterpoll/matterpoll/blob/master/CONTRIBUTING.md#translation-process-for-new-languages) to create the file?

Thank you for the review!

I have uploaded new patch to apply that :smile:

2020-09-15 10:18 UTC, hanzei requested changes
Thanks for the translation :+1: 

Two small requests

2020-09-15 10:18 UTC, hanzei commented on CONTRIBUTING.md
> +- Korean: [@potatogim](https://github.com/potatogim)
Please order that list alphabetically

2020-09-15 10:18 UTC, hanzei commented on README.md
> +- Korean
Same here

2020-09-16 04:51 UTC, potatogim commented on CONTRIBUTING.md
> +- Korean: [@potatogim](https://github.com/potatogim)
Yes, I did that :smile:

2020-09-17 08:38 UTC, hanzei approved these changes
Awesome :rocket:

2020-09-18 13:03 UTC, kaakaa approved these changes
Great 👍

2020-09-18 13:04 UTC, merged