Use French instead of France
matterpoll/matterpoll pull request #365
Opened 2020-12-18 23:04 UTC by duboism

This PR corrects a simple typo in `README.md` (section Localization): `France` should be `French`.

2020-12-19 05:43 UTC, kaakaa commented
Thanks @duboism! Your changes look fine, but could you please fix `France` in [`CONTRIBUTING.md`](https://github.com/matterpoll/matterpoll/blob/master/CONTRIBUTING.md) as well?

2020-12-19 06:43 UTC, hanzei requested changes
Thanks for the fix :+1: 

Could you please also update `CONTRIBUTING.md`?

2020-12-19 13:50 UTC, duboism commented
@kaakaa @hanzei thanks for pointing the typo in `CONTRIBUTING.md` (I should have checked). It's fixed.

2020-12-26 05:11 UTC, kaakaa approved these changes
Thanks 👍

2021-01-07 09:48 UTC, hanzei approved these changes

2021-01-07 09:48 UTC, merged

2021-01-07 09:48 UTC, hanzei commented
Thanks for the contribution @duboism :+1:

2021-01-11 11:01 UTC, duboism commented
Thanks for merging this and most importantly for the plugin.